networks: 
  safeeating_net:
    driver: bridge
services:
  safeeating_db:
    image: postgis/postgis:16-3.4-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    networks:
      - safeeating_net
    
  safeeating_back:
    build: ./backend
    restart: always
    volumes:
      - ./static/:/code/static/
      - ./media/:/code/media/
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DOMAIN_NAME=$DOMAIN_NAME
      - DEPLOY=True
      - DJANGO_EMAIL=admin@localhost
      - DJANGO_SUPERUSER_USERNAME=admin@localhost
      - DJANGO_SUPERUSER_PASSWORD=12
    networks:
      - safeeating_net
    depends_on:
      - safeeating_db
  safeeating_front:
    build: 
      context: ./frontend
      args:
        - VITE_ESTABLISHMENT_API=http://localhost/api
        - VITE_MEDIA_URL=http://localhost
    networks:
      - safeeating_net 
  fileserver:
    build: ./nginx
    volumes:
      - ./static:/static
      - ./media:/media
    depends_on:
      - safeeating_back
    networks:
      - safeeating_net
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - safeeating_back
      - safeeating_front
      - fileserver
    ports:
      - "80:80"
    networks:
      - safeeating_net
volumes:
  db_data: