networks: 
  safeeating_net:
    driver: bridge
services:
  safeeating_db:
    image: postgis/postgis:16-3.4-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    networks:
      - safeeating_net
    
  safeeating_back:
    build: ./backend
    restart: always
    volumes:
      - ./static/:/code/static/
      - ./media/:/code/media/
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DOMAIN_NAME=$DOMAIN_NAME
      - DEPLOY=True
    networks:
      - safeeating_net
    depends_on:
      - safeeating_db
  safeeating_front:
    build: ./frontend
    networks:
      - safeeating_net 
  fileserver:
    build: ./nginx
    volumes:
      - ./static:/static
      - ./media:/media
    depends_on:
      - safeeating_back
    networks:
      - safeeating_net
  caddy:
    build: ./caddy
    depends_on:
      - safeeating_back
      - safeeating_front
      - fileserver
    ports:
      - "80:80"
      - "443:443"
    networks:
      - safeeating_net
    environment:
      - SERVER_EMAIL=$SERVER_EMAIL
      - SERVER_NAME=$DOMAIN_NAME
volumes:
  db_data: