FROM python:3.11.6-slim-bullseye

RUN mkdir /code
WORKDIR /code
COPY . .

RUN apt update
RUN apt install -y gdal-bin
RUN pip install -r requirements.txt
RUN pip install gunicorn
RUN chmod +x back_entrypoint.sh

ENV DJANGO_SUPERUSER_USERNAME=admin@localhost
ENV DJANGO_SUPERUSER_EMAIL=admin@localhost
ENV DJANGO_SUPERUSER_PASSWORD=12

ENTRYPOINT ["./back_entrypoint.sh"]