version: '3'
networks: 
  safe_eating_dev:
    driver: bridge
services:
  safeeating_db:
    image: postgis/postgis:16-3.4-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=safeeating
      - POSTGRES_USER=safeeating
      - POSTGRES_PASSWORD=safeeating
    ports:
      - "5432:5432"
    networks:
      - safe_eating_dev
volumes:
  db_data: