FROM python:3.11.6-slim-bullseye
RUN mkdir /code
WORKDIR /code
COPY . .
RUN apt update
RUN apt install -y gdal-bin
RUN pip install -r requirements.txt
RUN pip install gunicorn
RUN chmod +x back_entrypoint.sh
ENTRYPOINT ["./back_entrypoint.sh"]