# Generated by Django 5.0.1 on 2024-04-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation', '0002_adaptation_url'),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='adaptation',
            field=models.ManyToManyField(blank=True, to='adaptation.adaptation'),
        ),
    ]
