# Generated by Django 5.0.1 on 2024-04-14 16:49

import rating.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating", "0002_rating_adaptation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratingimage",
            name="url",
            field=models.ImageField(upload_to=rating.models.RatingImage.upload_path),
        ),
    ]
