# Generated by Django 5.0.1 on 2024-06-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating", "0003_alter_ratingimage_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ratingimage",
            name="rating",
        ),
        migrations.AddField(
            model_name="ratingimage",
            name="rating",
            field=models.ManyToManyField(to="rating.rating"),
        ),
    ]
