# Generated by Django 5.0.1 on 2024-06-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("establishment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="establishmentimage",
            name="establishment",
        ),
        migrations.AddField(
            model_name="establishmentimage",
            name="establishment",
            field=models.ManyToManyField(to="establishment.establishment"),
        ),
    ]
