# Generated by Django 5.0.1 on 2024-03-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation', '0001_initial'),
        ('establishment', '0003_establishment_adaptation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='adaptation',
            field=models.ManyToManyField(blank=True, to='adaptation.adaptation'),
        ),
        migrations.AlterField(
            model_name='establishmentimage',
            name='image',
            field=models.ImageField(upload_to='media/establishment_pics'),
        ),
    ]
