# Generated by Django 5.0.1 on 2024-03-24 10:34

import establishment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0004_alter_establishment_adaptation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishmentimage',
            name='image',
            field=models.ImageField(upload_to=establishment.models.EstablishmentImage.upload_path),
        ),
    ]
