# Generated by Django 5.0.1 on 2024-03-31 19:19

import adaptation.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adaptation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adaptation",
            name="url",
            field=models.ImageField(
                null=True, upload_to=adaptation.models.Adaptation.upload_path
            ),
        ),
    ]
