name: Pytest

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tox:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    strategy:
      matrix:
        python-version: [3.11.6]
    services:
      postgres:
        image: postgis/postgis:16-3.4-alpine
        env:
          POSTGRES_USER: safeeating
          POSTGRES_DB: safeeating
          POSTGRES_PASSWORD: safeeating
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run apt update
        run: sudo apt-get update
      - name: Install gdal library
        run: sudo apt-get install -y gdal-bin
      - name: Install dependencies
        run: pip install -r requirements-dev.txt
      - name: Run pytest
        run: pytest .
