name: Tox

on: [push, pull_request]

jobs:
  tox:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    strategy:
      matrix:
        python-version: [3.11.6]
    services:
      safeeating_db:
        image: postgis/postgis:16-3.4-alpine
        env:
          POSTGRES_USER: safeeating
          POSTGRES_DB: safeeating
          POSTGRES_PASSWORD: safeeating
        ports:
          - 5432/tcp

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: pip install tox==4.12.1
      - name: Run tox
        run: touch .env & echo "POSTGRES_DB=safeeating" >> .env & echo "POSTGRES_USER=safeeating" >> .env & echo "POSTGRES_PASSWORD=safeeating" >> .env & echo "DB_HOST=safeeating_db" >> .env & echo "DB_PORT=5432" >> .env & tox
