name: Lint  && Vitest

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.7.0"

      - name: Install dependencies
        run: npm ci

      - name: Run Vite linter
        run: npm run lint
        
      - name: Run Unit Tests
        run: npx vitest